app = "hnasurgerybot"
primary_region = "iad" # США, Virginia

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"  # оставляем
  min_machines_running = 1     # 1 машина всегда работает
  processes = ["app"]

[[vm]]
  memory = "512mb"  # 512mb
  cpu_kind = "shared"
  cpus = 1
