app = "hnasurgerybot"
primary_region = "iad"  # США, Virginia

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"   # управляет дополнительными машинами, основная работает всегда
  min_machines_running = 1      # 1 машина всегда онлайн
  processes = ["app"]

[[vm]]
  memory = "512mb"  # минимальное потребление
  cpu_kind = "shared"
  cpus = 1
